{% set name = "sphinx-pythia-theme" %}
{% set version = "2022.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-pythia-theme-{{ version }}.tar.gz
  sha256: 6977add810ec5074b61b33e3ff01d5d333f3f718d1a107f6c1a6b392eafa74e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - sphinx-book-theme >=0.1.7

test:
  imports:
    - sphinx_pythia_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ProjectPythia/sphinx-pythia-theme
  summary: Sphinx Pythia Theme
  dev_url: https://github.com/ProjectPythia/sphinx-pythia-theme
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kmpaul
