{% set name = "sphinx-pythia-theme" %}
{% set version = "2024.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2f14069bcde059050cf1ab1d86a1efcad470320dececc52b7df4414f50b9c9a7

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --find-links --no-index --ignore-installed --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sphinx >=5
    - sphinx-book-theme >=1.0.0
    - sphinx-design

test:
  imports:
    - sphinx_pythia_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ProjectPythia/sphinx-pythia-theme
  summary: Sphinx Pythia Theme
  dev_url: https://github.com/ProjectPythia/sphinx-pythia-theme
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brian-rose
    - erogluorhan
    - jukent
