{% set name = "sphinx-pythia-theme" %}
{% set version = "2024.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-pythia-theme-{{ version }}.tar.gz
  sha256: d2739f7203643650436bc4ecd52838e824520265fc8e669363269503711eea9b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --find-links --no-index --ignore-installed --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - sphinx >=5
    - sphinx-book-theme >=1.0.0
    - sphinx-design

test:
  imports:
    - sphinx_pythia_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ProjectPythia/sphinx-pythia-theme
  summary: Sphinx Pythia Theme
  dev_url: https://github.com/ProjectPythia/sphinx-pythia-theme
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brian-rose
    - erogluorhan
    - jukent
